name: raro_budget
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_card: ^2.0.0
  shimmer: ^2.0.0
  cpf_cnpj_validator: ^2.0.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_modular: ^3.3.1
  intl: ^0.17.0
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0

dev_dependencies:
  build_runner: ^2.0.6
  modular_codegen:
  mobx_codegen: ^2.0.1+3
  flutter_test:
    sdk: flutter
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_budget.png
    - assets/images/logo_budget_blue.png
    - assets/images/logo_raro.png
    - assets/images/onboarding_background.png
    - assets/images/onboarding_background_novector.png
    - assets/images/budget_icon_only.png
    - assets/images/budget_logo_text_only.png
    - assets/images/budget_subtitle_only.png
    - assets/images/powered_by_raro.png
    - assets/images/onboarding_vector.png
    - assets/images/logo_facebook.png
    - assets/images/logo_google.png
    - assets/icons/meal_icon.png
    - assets/icons/education_icon.png
    - assets/icons/transport_icon.png
    - assets/icons/trip_icon.png
    - assets/icons/payments_icon.png
    - assets/icons/others_icon.png
    - assets/icons/bank_slip_icon.png
    - assets/icons/doc_icon.png
    - assets/icons/pix_icon.png
    - assets/icons/ted_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
